CookSpaces/Chief/urls.py
from django.urls import path
from . import views

app_name = "Chief"

urlpatterns  = [
    path('Chief/register/', views.register_chife, name='register_chife'),
    path('Chief/profile/<user_name>', views.profile_view, name='profile'),
    path('Chief/all/', views.all_chief_view, name='all_chief_view'),
    path("Chief/update/", views.update_user_view, name="update_user_view"),


    


]

CookSpaces/CookSpaces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("", include("accounts.urls")),
    path("", include("KitchenOwner.urls")),
    path("", include("Renters.urls")),
    path("", include("Chief.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CookSpaces/KitchenOwner/urls.py
from django.urls import path
from . import views

app_name = "KitchenOwner"

urlpatterns  = [
 path("kitchen/Owner/Register",views.register_owner,name="register_owner"),
 path("<owner_username>/profile",views.owner_profile,name="owner_profile"),
 path("add/kitchen",views.add_kitchen,name="add_kitchen"),
 path("<kitchen_id>/kitchen/details",views.kitchen_details,name="kitchen_details"),
 path("<owner_username>/update/profile",views.update_owner_profile,name="update_owner_profile"),
 path("All/kitchens/",views.all_kitchens,name="all_kitchens"),
 path("<kitchen_id>/rental/request/",views.rental_request,name="rental_request"),
 path("<owner_id>/orders/",views.owner_orders,name="owner_orders"),
 path("<order_id>/reject/order/",views.reject_order,name="reject_order"),
 path("<order_id>/accept/order/",views.accept_order,name="accept_order"),
 path("<order_id>/order/details/",views.order_details,name="order_details"),
 path("<order_id>/final/offer/",views.final_offer,name="final_offer"),
 path("All/kitchens/search/",views.search_cities,name="search_cities"),

]   

CookSpaces/Renters/urls.py
from django.urls import path
from . import views

app_name = "Renters"

urlpatterns  = [
    path("register/renter",views.register_renter, name="register_renter"),
    path("profile/<user_id>/renter",views.profile, name="profile"),
    path("<user_id>/my/orders/",views.my_order, name="my_order"),
    path("profile/update/<user_id>",views.update_profile, name="update_profile"),
    path("saved/<kitchen_id>/kitchens",views.add_remove_saved_view, name="add_remove_saved_view"),
    path("user/saved/", views.saved_kitchens, name="saved_kitchens"),
]

CookSpaces/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns  = [
    path("register/", views.register_user, name="register"),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

CookSpaces/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns  = [
    path("", views.home, name="home"),
    path("delete/<kitchen_id>", views.delete_kitchen, name="delete_kitchen"),
    path("articles/", views.all_article, name="articles"),
    path("articles/detail/<kitchen_id>", views.article_detail, name="article_detail"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path('contact/messages', views.messages, name='message'),
    path("reviews/add/<kitchen_id>", views.add_review, name="add_review"),
]

CookSpaces/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator  
from KitchenOwner.models import Kitchen

# Create your models here.
class Article(models.Model):

    title = models.CharField(max_length=1000)
    content = models.TextField()
    poster = models.ImageField(upload_to='poster/')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title
    
class Contact(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, default="")
    last_name = models.CharField(max_length=50, default="")
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.user.username
    
class Review(models.Model):

    kitchen = models.ForeignKey(Kitchen, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    evaluation = models.PositiveIntegerField( validators=[MinValueValidator(1), MaxValueValidator(5)], null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.user.username

CookSpaces/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import Contact, Article, Review
from KitchenOwner.models import Kitchen, Equipment
from Renters.models import BookMark
import math

def home(request:HttpRequest):
    
    if request.user.is_authenticated:
        print(request.user.first_name)
    
    kitchens = Kitchen.objects.all()[:3]
    articles = Article.objects.all()[:4]
    
    return render(request, "main/home.html",  {"kitchens":kitchens, "articles":articles})

def delete_kitchen(request:HttpRequest, kitchen_id):

    #limit access to this view for only staff
    if not request.user.username:
        return render(request, "no_permission.html")

    try:
        kitchen = Kitchen.objects.get(pk=kitchen_id)
        kitchen.delete()
    except Exception as e:
        print(e)
    

    return redirect("main:home")

def all_article(request:HttpRequest):
    
    kitchens = Article.objects.all()
    
    # #calculate the page content
    # limit = 4
    # pages_count = [str(n) for n in range(1, math.ceil(kitchens.count()/limit)+1)] #use list comprehension to convert number to string number
    # start = (int(request.GET.get("page", 1))-1)*limit
    # end = (start)+limit
    
    # #apply the limit/slicing
    # kitchens = kitchens[start:end]

    # # print(start, end)
    
# "pages_count":pages_count
    return render(request, "main/articles.html", {"kitchens" : kitchens })

def article_detail(request :HttpRequest,kitchen_id):
    try:
        #getting a kitchen detail
        article = Article.objects.get(pk=kitchen_id)
    except Article.DoesNotExist:
        return render(request, "404.html")
    except Exception as e:
        print(e)
        
    return render(request, "main/article_detail.html", {"article" : article})

def about(request:HttpRequest):
    
    return render(request, "main/about.html")

def contact(request:HttpRequest):
        if request.method == 'POST':
            try:
                new_con = Contact(
                    user = request.user,
                    first_name = request.POST["first"],
                    last_name = request.POST["last"],
                    email = request.POST["email"],
                    message = request.POST['message']
                )
                new_con.save()
                
            except Exception as e:
                print(e)
            
            # return redirect('main:message')
        return render(request, "main/contact.html")

def messages(request:HttpRequest):

    if not request.user.is_superuser:
        return render(request, "no_permission.html")

    message = Contact.objects.all()[0:3]

    return render(request,'main/messages.html', {'message' : message})

def add_review(request:HttpRequest, kitchen_id):
    if not request.user.is_authenticated:
        return redirect("accounts:login")
    
    if request.method == "POST":
        try:
            kitchens= Kitchen.objects.get(pk=kitchen_id)
            new_review = Review(kitchen=kitchens,
                                  user=request.user, 
                                  content=request.POST["content"],
                                  evaluation=request.POST["evaluation"])
            new_review.save()
        except Exception as e:
                print(e)
    
    return redirect("KitchenOwner:kitchen_details", kitchen_id=kitchens.id)

CookSpaces/main/templates/main/articals.html
{% extends 'main/base.html' %}
{% block title %}CookSpaces | ARTICALS{% endblock %}

{% block style %}

{% endblock %}

{% block content %}

{% endblock %}

CookSpaces/main/templates/main/article_detail.html
{% extends 'main/base.html' %}
{% block title %}CookSpaces | ARTICLES{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}



<section style="padding-top:150px;">

    <div class="row" >
        <div class="col order-2">
            <img src="{{article.poster.url}}" alt="poster" style="width:500px;">
        </div>
        <div class="col order-1">
            <h1 class="display- mb-5" style="color: #8EB89C; direction: rtl; text-align: center; padding-top:10px ;" > <br><u class="text-warning"><span style="color: #1E4D57;font-size: 150%;">{{article.title}}</span></u></h1>
        </div>

    </div>
    <div>
        <p style="padding-top:50px;color: rgb(23, 23, 23); direction: rtl; font-size: 25px; white-space: pre-line; padding-right: 30px; padding-left: 30px;">{{article.content}}</p>
    </div>

</section>
{% endblock %}

CookSpaces/main/templates/main/articles.html
{% extends 'main/base.html' %}
{% block title %}CookSpaces | ARTICLES{% endblock %}

{% block styles %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Diplomata&family=Londrina+Outline&family=Whisper&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Diplomata&family=Lobster&family=Londrina+Outline&family=Whisper&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

    <!-- Font Awsome -->
    <script src="https://kit.fontawesome.com/351e3a5348.js" crossorigin="anonymous"></script>

    <!--  Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
{% endblock %}

{% block content %}

<section style="padding-top:150px;">
    <div class="container" >        
        <h2 class=" title h1 fw-bold"> <u class="text-warning"><span style="color: #00815b; margin-top: 500px; ">  مواضيع تهمك وتفيدك </span></u></h2>
        <div class="row d-flex justify-content-center" style="background-color: #dddcd9; border-radius: 30px; padding: 50px;">
            {% for kitchen in kitchens %}
            <div class="col-4" style="margin-bottom: 10px; ">
                <a href="{% url 'main:article_detail' kitchen.id %}" class="notititle text-decoration-none" style="color: rgba(0, 0, 0, 0.582);" >
                <div class="notification">
                    <div class="notiglow"></div>
                    <div class="notiborderglow"></div>
                    <div class="notititle">{{kitchen.title}}</div>
                    
                      اقرأ المزيد
                  </a>
                </div>
            </div>        
            {% endfor %}
        </div>                    
    </div>
</section>

{% endblock %}

CookSpaces/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>

    <!-- CSS Style -->
    <link rel="stylesheet" href="{% static 'CSS/style.css' %}">

    <!-- Google Icon & Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Angkor&family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&family=Diplomata+SC&family=El+Messiri:wght@400..700&family=Fascinate&family=Londrina+Outline&family=Madimi+One&family=Oi&family=Revalia&family=Rubik+Spray+Paint&family=Satisfy&family=The+Nautigal:wght@400;700&display=swap" rel="stylesheet">
    
    <link href="/static/CSS/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Animate CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

    <!-- Google Font  -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

    <!-- Font Awsome -->
    <script src="https://kit.fontawesome.com/351e3a5348.js" crossorigin="anonymous"></script>

    <!--  Bootstrap CSS -->
    
    <link rel="stylesheet" href="/static/CSS/bootstrap-icons.min.css">


    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    {% block styles %}
    {% endblock %}

  </head>
  <!-- <body style="background: linear-gradient(#ffffff, #a8a8a893); background-attachment:  fixed;"> -->
    <body style="background: #fff; background-attachment:  fixed; direction: rtl;">

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-collapse fixed-top p-2 mb-1 " style="background-color: #fff;">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand d-flex flex-column justify-content-center align-items-center" href="{% url 'main:home' %}">
            <h4 style="text-align: center;">CookSpaces</h4></a>

                    
          <div id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0 gap-2">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'KitchenOwner:all_kitchens' %}">المطابخ</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:articles' %}">مقالات</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:about' %}">من نحن</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:contact' %}">تواصل معنا</a>
              </li>
            </ul>
          </div>

          <div class="d-flex gap-3 align-items-center">
            {% if request.user.is_authenticated and request.user.is_superuser %}
            <div class="d-flex gap-2">
              <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                   مرحبا <strong>{{request.user.username }}</strong> (admin)
                </a>

                <ul class="dropdown-menu" style="background: #e4e4e4b7;">
                  <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">تسجيل خروج</a></li>
                </ul>
              </div>
            </div>
          {% elif request.user.is_authenticated %}
            {% for group in request.user.groups.all %}
              {% if group.name == 'Kitchen_owner' %}
                  <a class="btn btn-dark" href="{% url 'KitchenOwner:add_kitchen'  %}" style="padding: 5px;">إضافة مطبخ</a>
                  
                  <div class="d-flex gap-2">
                    <div class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        مرحبا, <strong>{{request.user.username }}</strong>
                      </a>
                      <ul class="dropdown-menu" style="background: #e4e4e4b7;">
                        <li><a class="dropdown-item" href="{% url 'KitchenOwner:owner_profile' request.user.username %}">الملف الشخصي</a></li>
                        <li><a class="dropdown-item" href="{% url 'KitchenOwner:owner_orders' request.user.id %}">طلباتي</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">تسجيل الخروج</a></li>
                      </ul>
                    </div>
                  </div>
              {% endif %}

              {% if group.name == 'Renter' %}
              <!-- <a class="btn btn-dark" href="{% url 'Chief:all_chief_view' %}" style="padding: 5px;">عرض جميع الطهاة</a> -->

              <div class="d-flex gap-2">
                <div class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                     مرحبا <strong>{{request.user.username }}</strong> 
                  </a>
                  <ul class="dropdown-menu" style="background: #e4e4e4b7;">
                    <li><a class="dropdown-item" href="{% url 'Renters:profile' request.user.id %}">الملف الشخصي</a></li>

                    <li><a class="dropdown-item" href="{% url 'Renters:saved_kitchens' %}">مطابخي المحفوظة</a></li>
                    <li><a class="dropdown-item" href="{% url 'Renters:my_order' request.user.id %}">طلباتي</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">تسجيل الخروج</a></li>
                  </ul>
                </div>
              </div>
              {% endif %}

              <!-- {% if group.name == 'Chef' %}
              <div class="d-flex gap-2">
                <div class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                     <strong>{{request.user.username }}</strong> مرحبا شيف
                  </a>
                  <ul class="dropdown-menu" style="background: #e4e4e4b7;">
                    <li><a class="dropdown-item" href="{% url 'Chief:profile' request.user.id %}">الملف الشخصي</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">تسجيل الخروج</a></li>
                  </ul>
                </div>
              </div>
              {% endif %} -->
            {% endfor %}

            {% else %}
            <div >
              <a href="{% url 'accounts:register' %}" style="color: #02020b; text-decoration: none;"  >تسجيل جديد</a>
              /
              <a href="{% url 'accounts:login' %}" style="color: #02020b; text-decoration: none;">تسجيل دخول</a>
            </div>
  
            {% endif %}
          </div>
            

      </nav>

      <script>
        const navEl = document.querySelector('.navbar');
        window.addEventListener('scroll', () => {
            if (window.scrollY >= 56){
                navEl.classList.add('navbar-scrolled');
            } else if (window.scrollY < 56){
                navEl.classList.remove('navbar-scrolled')
            }
        })
      </script>
    </div>
        {% block content %}
        {% endblock %}

        <!-- Footer -->

        <footer class="bd-footer">
            <hr style="margin-top: 2rem;">
            <div class="container py-3 py-md-3 px-3 px-md-3 text-body-secondary">
              <div class="row">
                <div class="col-4 mb-3">
      
                  <a class="navbar-brand d-flex flex-column align-items-center" href="{% url 'main:home' %}">
                    <h4 class="fa-fade" style="text-align: center;">CookSpaces</h4></a>
                    <!-- <ul class="list-unstyled d-flex flex-row justify-content-center gap-5 mt-4">
                    <li><a href="#" style="color: #02020b; font-size: larger;"><i class="fa-brands fa-facebook"></i></a></li>
                    <li><a href="#" style="color: #02020b; font-size: larger;"><i class="fa-brands fa-instagram"></i></a></li>
                    <li><a href="#" style="color: #02020b; font-size: larger;"><i class="fa-brands fa-x-twitter"></i></a></li>
                    <li><a href="#" style="color: #02020b; font-size: larger;"><i class="fa-brands fa-youtube"></i></a></li>
                  </ul> -->
                </div>
      
                <div class="col-4 mb-3">
                  <ul class="list-unstyled d-flex justify-content-center gap-4">
                    <li><a href="/" style="color: #080822; text-decoration: none;">الرئيسية</a></li>
                    <li><a href="{% url 'KitchenOwner:all_kitchens' %}" style="color: #080822; text-decoration: none;">المطابخ</a></li>
                    <li><a href="{% url 'main:about' %}" style="color: #080822; text-decoration: none;">من نحن</a></li>
                    <li><a href="{% url 'main:contact' %}" style="color: #080822; text-decoration: none;">تواصل معنا</a></li>
                  </ul>
                </div>
      
                <div class="col-4">
                  <div class="d-flex justify-content-center">
                    <h5>شاركنا رأيك</h5>
                  </div>
                  <ul class="list-unstyled d-flex flex-row justify-content-center gap-5 mt-2">
                    <li><a href="#" style="color: #02020b; font-size: larger;"><i class="fa-brands fa-facebook"></i></a></li>
                    <li><a href="#" style="color: #02020b; font-size: larger;"><i class="fa-brands fa-instagram"></i></a></li>
                    <li><a href="#" style="color: #02020b; font-size: larger;"><i class="fa-brands fa-x-twitter"></i></a></li>
                  </ul>
                </div>
              </div>
      
              <div class="row" style="direction: ltr;">
                <hr>
                <div class="col d-flex" style="justify-content: space-between;">
                  © 2024 by. CookSpaces Team, All rights reserved.
                  <div class="d-flex gap-3">
                    <a href="#" style="color: #080822; text-decoration: none;">الشروط والأحكام</a>
                    <a href="#" style="color: #080822; text-decoration: none;">سياسة الخصوصية</a>
                  </div>
                </div>
              </div>
            </div>
          </footer>      

    <script src="/static/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="@@path/vendor/countup.js/dist/countUp.umd.js"></script>
  </body>
</html>

CookSpaces/main/templates/main/messages.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} CookSpaces | USER MESSAGES {% endblock %}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 120px;">
        <div class="col">
            <h1>رسائل المستخدمين</h1>
            <div class="row mt-4">
                {% for msg in message %}
                <div class="col-4 ">
                    <div class="d-flex flex-column p-3 rounded-4 w-100" style="border-left: 5px groove; border-right: 5px groove;">
                        <div class="d-flex flex-row gap-2">
                            <span class="material-symbols-rounded ">account_circle</span>
                            <h5>{{msg.first_name}} {{msg.last_name}}</h5>
                        </div>

                        <h6><a href="mailto:{{ msg.email }} " target='_blank' rel=noopener noreferrer>{{ msg.email }}</a></h6>
                        <h6>{{ msg.message }}</h6>
                        <h6 class="text-muted">{{ msg.created_at }}</h6>
                    </div>
                </div>
                {% endfor %}
            </div> <!--row 2-->

            <div class="row mt-4 ">
                <div class="col d-flex justify-content-center">
                    <a href="{% url 'main:contact' %}" class="btn btn-outline-dark">Back to Contact Page...</a>
                </div>
            </div>
        </div>
    </div> <!--row 1-->
</div>
{% endblock %}