CookSpaces/CookSpaces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("", include("accounts.urls")),
    path("", include("KitchenOwner.urls")),
    path("", include("Renters.urls")),
    path("", include("Chief.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CookSpaces/KitchenOwner/urls.py
from django.urls import path
from . import views

app_name = "KitchenOwner"

urlpatterns  = [
 path("kitchen/Owner/Register",views.register_owner,name="register_owner"),
 path("<owner_username>/profile",views.owner_profile,name="owner_profile"),
 path("add/kitchen",views.add_kitchen,name="add_kitchen"),
 path("<kitchen_id>/kitchen/details",views.kitchen_details,name="kitchen_details"),
 path("<owner_username>/update/profile",views.update_owner_profile,name="update_owner_profile"),
 path("All/kitchens/",views.all_kitchens,name="all_kitchens"),
 path("<kitchen_id>/rental/request/",views.rental_request,name="rental_request"),
 path("<owner_id>/orders/",views.owner_orders,name="owner_orders"),
 path("<order_id>/reject/order/",views.reject_order,name="reject_order"),
 path("<order_id>/accept/order/",views.accept_order,name="accept_order"),
 path("<order_id>/order/details/",views.order_details,name="order_details"),
 path("<order_id>/final/offer/",views.final_offer,name="final_offer"),
 path("All/kitchens/search/",views.search_cities,name="search_cities"),

]   

CookSpaces/Renters/urls.py
from django.urls import path
from . import views

app_name = "Renters"

urlpatterns  = [
    path("register/renter",views.register_renter, name="register_renter"),
    path("profile/<user_id>/renter",views.profile, name="profile"),
    path("<user_id>/my/orders/",views.my_order, name="my_order"),
    path("profile/update/<user_id>",views.update_profile, name="update_profile"),
    path("saved/<kitchen_id>/kitchens",views.add_remove_saved_view, name="add_remove_saved_view"),
    path("user/saved/", views.saved_kitchens, name="saved_kitchens"),
]

CookSpaces/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns  = [
    path("", views.home, name="home"),
    path("delete/<kitchen_id>", views.delete_kitchen, name="delete_kitchen"),
    path("articles/", views.all_article, name="articles"),
    path("articles/detail/<kitchen_id>", views.article_detail, name="article_detail"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path('contact/messages', views.messages, name='message'),
    path("reviews/add/<kitchen_id>", views.add_review, name="add_review"),
]

CookSpaces/Renters/models.py
from django.db import models
from accounts.models import KitchenOwner,Renter
from KitchenOwner.models import Kitchen
from django.core.validators import MinValueValidator, MaxValueValidator      
from django.contrib.auth.models import User


class Order(models.Model):
    state = models.TextChoices("status",["مقبولة","مرفوضة", "تحت المراجعة","مدفوعة"])
    
    renter = models.ForeignKey(Renter,on_delete=models.CASCADE)
    kitchen = models.ForeignKey(Kitchen,on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    note = models.TextField()
    status = models.CharField(max_length=64,choices=state.choices)
    created_at = models.DateTimeField(auto_now_add=True)
    price = models.FloatField(null=True)

    def __str__(self) -> str:
        return self.kitchen.title

class Payment(models.Model):
    
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    name = models.CharField(max_length=2048)
    card_number = models.IntegerField()
    expired_year = models.DateField(null=True)
    expired_month=models.DateField(null=True)
    cvv = models.IntegerField()

class BookMark(models.Model):
    
    kitchen = models.ForeignKey(Kitchen, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.kitchen.title    

CookSpaces/Renters/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.models import User,Group
from django.contrib.auth import authenticate
from django.db import IntegrityError,transaction
from accounts.models import KitchenOwner,Renter
from KitchenOwner.models import Kitchen
from Renters.models import BookMark ,Order
from django.conf import settings
from django.core.mail import EmailMessage

def register_renter(request:HttpRequest):
    msg = None

    if request.method == "POST":
        try:
            with transaction.atomic():
                
                new_user = User.objects.create_user(
                    username=request.POST["username"], 
                    email=request.POST["email"], 
                    first_name=request.POST["first_name"], 
                    last_name=request.POST["last_name"], 
                    password=request.POST["password"]
                    )
                new_user.save()

                if not new_user.groups.filter(name='Renter').exists():
                    group = Group.objects.get(name="Renter")
                    new_user.groups.add(group)

                register_renter = Renter(
                    user=new_user, 
                    about=request.POST["about"],
                    avatar=request.FILES.get("avatar", Renter.avatar.field.get_default()),
                    phone=request.POST["phone"]
                    )
                register_renter.save()

            return redirect("accounts:login")
        
        except IntegrityError as e:
            msg = "This username is already taken. Please choose a different username."
            print(e)

        except Exception as e:
            msg = f"Something went wrong. Please try again. {e}"
            print(e)
    
    return render(request, "renters/register_renter.html", {"msg" : msg})

def profile(request:HttpRequest, user_id):
    try:
        user_profile = User.objects.get(pk=user_id)
        
    except:
        return render(request, "404.html")

    return render(request, "renters/profile.html",{"user_profile": user_profile,})


def update_profile(request:HttpRequest, user_id):
    msg = None

    if not request.user.is_authenticated:
        return redirect("accounts:login")
    
    try: 
        user_info = User.objects.get(pk=user_id)
    except:
        return render(request, "404.html")
    
    if request.method == "POST":
        
        try:

            with transaction.atomic():
                user:User = request.user

                user.first_name = request.POST["first_name"]
                user.last_name = request.POST["last_name"]
                user.email = request.POST["email"]

                user.save()
                
                try:
                    profile:Renter= user.renter
                except Exception as e:
                    profile =Renter(user=user)

                profile.about = request.POST["about"]
                profile.avatar = request.FILES.get("avatar", profile.avatar)
                profile.phone = request.POST["phone"]

                profile.save()

                return redirect("Renters:profile", user_id=user.id)

        except Exception as e:
            msg = f"Something went wrong {e}"
            print(e)

    return render(request, "renters/profile_update.html", {"user_info":user_info, "msg" : msg})


def my_order(request:HttpRequest,user_id):
    orders=[]
    msg=''
    if "cat" in request.GET:
        orders= Order.objects.filter(status = request.GET["cat"],renter__user__id=user_id)
        print(request.GET["cat"])
        if not orders:
            msg="ليس لديك أي طلبات"
    else:
        orders = Order.objects.all().order_by("-created_at")

        
    return render(request, 'renters/my_order.html',{"status":Order.state.choices, "orders":orders,"msg":msg})



def accept(request: HttpRequest):
    
    if request.method == 'POST':
        user = request.user
        kitchen = user.order_set.all()  # Example, replace with actual retrieval logic
        total_price = sum(item.kitchen.price for item in kitchen)
        subject = 'حالة الطلب'
        message = f'السلام عليكم {user.username}, السعر: {total_price}ريال. شكرا لاختيارك خدماتنا! نحن نقدر تفضيلك وثقتك بنا ونتطلع إلى خدمتك مرة أخرى قريبًا,تم قبول الطلب.'
        send_html_email_to_user(subject, message, user.email)
        return render(request, 'renters/my_order.html', {'kitchen': kitchen, 'total_price': total_price,'message': message})
    

def send_html_email_to_user(subject,msg,user_email):
    subject = subject
    message = msg
    email_from =settings.EMAIL_HOST_USER
    recipient_list = [user_email]

    email = EmailMessage(subject, message, email_from, recipient_list)
    email.content_subtype = 'html'  # Enable HTML content
    try:
        email.send()
    except Exception as e:
        print(e)


def reject(request: HttpRequest):
    
    if request.method == 'POST':
        user = request.user
        kitchen = user.order_set.all()  # Example, replace with actual retrieval logic
        subject = 'حالة الطلب'
        message = f'السلام عليكم {user.username}, تم رفض الطلب'
        send_html_email_to_user(subject, message, user.email)  
        return render(request, 'renters/my_order.html', {'kitchen': kitchen,'message': message})


def send_html_email_to_user(subject,msg,user_email):
    subject = subject
    message = msg
    email_from =settings.EMAIL_HOST_USER
    recipient_list = [user_email]

    email = EmailMessage(subject, message, email_from, recipient_list)
    email.content_subtype = 'html'  # Enable HTML content
    try:
        email.send()
    except Exception as e:
        print(e)
        

def Payment(request: HttpRequest):
    
    return redirect('renters:my_order')   
        
def add_remove_saved_view(request: HttpRequest, kitchen_id):

    if not request.user.is_authenticated:
        return redirect("accounts:login")
    
    try:
        kitchen = Kitchen.objects.get(pk=kitchen_id)

        saved_kitchens = BookMark.objects.filter(user=request.user, kitchen=kitchen).first()

        if not saved_kitchens:
            saved = BookMark(user=request.user, kitchen=kitchen)
            saved.save()
        else:
            saved_kitchens.delete()
    
    except Exception as e:
        print(e)

    return redirect("KitchenOwner:kitchen_details", kitchen_id=kitchen_id)

def saved_kitchens(request:HttpRequest):

        return render(request, "renters/saved_kitchens.html")
    

CookSpaces/Renters/templates/renters/my_favorites.html
{% extends 'main/base.html' %}
{% block title %}CookSpaces | favorites{% endblock %}

{% block style %}

{% endblock %}

{% block content %}

{% endblock %}

CookSpaces/Renters/templates/renters/my_order.html
{% extends 'main/base.html' %}
{% block title %}CookSpaces | order{% endblock %}

{% block styles %}
<style>
	.cat {
    background-color: rgba(21, 128, 155, 0.377);
    color: white;
    align-self: flex-start;
}
.مقبولة {
    background-color: rgba(2, 90, 131, 0.664);
}
.مقبولة:hover {
    box-shadow: 0 0 20px rgba(2, 90, 131, 0.664);
}

.مرفوضة {
    background-color: rgba(255, 0, 0, 0.473);
}
.مرفوضة:hover {
    box-shadow: 0 0 20px rgba(255, 0, 0, 0.473);
}

.تحت {
    background-color: rgba(228, 183, 37, 0.473);
}
.تحت:hover {
    box-shadow: 0 0 20px rgba(228, 183, 37, 0.473);
}

.مدفوعة {
  background-color: rgba(0, 128, 0, 0.473);
}
.مدفوعة:hover {
  box-shadow: 0 0 20px rgba(0, 128, 0, 0.473);
}
    .panel-title {display: inline;font-weight: bold;}
    .checkbox.pull-right { margin: 0; }
    .pl-ziro { padding-left: 0px; }

</style>
{% endblock %}

{% block content %}
	<section style="direction: rtl; padding: 0; margin-top: 100px;">
		<div class="container">
			<div class="row">
                <h1>طلباتي</h1>
                <hr>
				<div class="col">
					<div class="d-flex justify-content-center align-items-center">
						<div class="d-flex gap-2">
							<a href="{% url 'Renters:my_order' request.user.id %}" class="p-2 ps-3 pe-3 rounded-pill cat text-decoration-none" style="color: rgb(3, 53, 36);">كل الطلبات</a>
							
							{% for val, key in status %}
								<a href="?cat={{val}}" class="p-2 ps-3 pe-3 rounded-pill cat {% if request.GET.cat == val %} {{ val }} {% endif %} text-decoration-none"  style="color: rgb(3, 53, 36);">{{val}}</a>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

<div class="container mt-5">
    <div class="row">

        <h5 class="d-flex justify-content-center">{{msg}}</h5>
        {% for order in orders %}
            <div class="col-4 d-flex mt-2">
                <div class="card" style="width: 20rem;">
                    <img src="{{order.kitchen.image.url}}" alt="poster" style="background-size: cover; height: 200px;">
                    <div class="card-body">
                        <h5 class="card-title">{{order.kitchen.title}}</h5>
                        <h6>Spcae: {{order.kitchen.space}} m<sup>2</h6>
                        <h6>Price: {{order.kitchen.price}} SR/{{order.kitchen.period}}</h6>
                        <h6 class="cat p-2 ps-3 pe-3 rounded-pill {{order.status}}" style="width: 50%; text-align: center;">{{ order.status }}</h6>
                        <div class="d-flex justify-content-end">
                            <a href="{% url 'KitchenOwner:kitchen_details' order.kitchen.id %}" class="btn btn-outline-warning" style="color: #6E6A6A;">التفاصيل</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

CookSpaces/Renters/templates/renters/profile.html
{% extends 'main/base.html' %}
{% block title %}CookSpaces | profile{% endblock %}

{% block styles %}
<style>
    /* Side bar  */
    /* .sidebar {
    width: 200px;
    background: #FFFFFF;
    position: fixed;
    height: 100%;
    border-radius: 30px;
    margin-left: 20px;
    margin-bottom: 20px;

  }
    
  .sidebar ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
  }
    
  .sidebar ul li {
    padding: 10px;
    text-align: center;
  }
    
  .sidebar ul li a {
    text-decoration: none;
    color: rgb(15, 62, 52);
    font-weight: bold;
  }
    
  .sidebar ul li button:hover {
    background: #ffd000;
    color: beige;
  } */
  body{
    background:#eee;
}

.card{
    border:none;
    width: 735px;
    position:relative;
    border-radius:8px;
    cursor:pointer;
    margin-right: 200px;
    padding-right: 10px;

}

.card:before{
    
    content:"";
    position:absolute;
    left:0;
    top:0;
    width:4px;
    height:100%;
    background-color:#5fe4bc;
    transform:scaleY(1);
    
    transition:all 0.5s;
    transform-origin: bottom
}

.card:after{
    
    content:"";
    position:absolute;
    left:0;
    top:0;
    width:4px;
    height:100%;
    background-color:#00815b;
    transform:scaleY(0);
    transition:all 0.5s;
    transform-origin: bottom
}

.card:hover::after{
    transform:scaleY(1);
}


.fonts{
    font-size:11px;
}

.social-list{
    display:flex;
    list-style:none;
    justify-content:center;
    padding:0;
}
/* 
.social-list li{
    padding:10px;
    color:#8E24AA;
    font-size:19px;
}

.buttons button {

    margin-right: 20px; /* إضافة مسافة بين الأزرار */
    /* text-decoration: none;
    background-color: black;
    
    

} */ 

</style>
{% endblock %}

{% block content %}

<section>    
    <div class="row">
        <div class=" d-flex justify-content-start" >
            {% if request.user == user_profile %}
                <!-- <a href="{% url 'Renters:update_profile' user_profile.id %}" class="btn btn-warning">Update</a> -->
                <a href="{% url 'Renters:update_profile' user_profile.id %}" class="btn btn-warning">
                    <i class="material-symbols-outlined">edit_square</i> Update
                </a>
            {% endif %}
        </div>
        <div class="col-md-7">
            
            
            <div class="card">
                
                <div class="text-center">
                  <img src="{{ user.renter.avatar.url }}" alt="Profile Image" class="img-fluid rounded-circle" style="width: 200px;">
                  <h5>@{{user_profile.username}}</h5>

                </div>
                
                <div class="text-center mt-3">
                    <span class="bg-secondary px-3 rounded text-white">Pro</span>
                    <h3 style="text-transform: capitalize;">{{user_profile.first_name}} {{ user_profile.last_name}}</h3>
                    <a href="mailto:{{user_profile.email}}">{{ user_profile.email }}</a>
                    <a href="tel:{{user_profile.phone}}">{{ user_profile.phone }}</a>
                    
                    
                    <div class="px-4 mt-1">
                      <p class="mt-2">{{ user.renter.about }}</p>
                    
                    </div>
                    
                     
                    
                    <div class="buttons mt-5">
                            <a href="{% url 'Renters:my_order' user.renter.id %} " class="btn " style="background-color: #272928;margin-top: 40px; "><span style="color: #F4F2EE;"> طلباتي</span></a>
                            <a href="{% url 'Renters:saved_kitchens' %}" class="btn " style="background-color: #272928;margin-top: 40px; "><span style="color: #F4F2EE;"> المطابخ المحفوظة</span></a>
                    </div>
                    
                    
                </div>
                
               
                
                
            </div>
            
        </div>
        
    </div>
    
</section>


{% endblock %}

CookSpaces/Renters/templates/renters/profile_update.html
{% extends 'main/base.html' %}
{% block title %}CookSpaces | profile{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
<section>
    {% if msg %}
        <div class="alert alert-danger">{{msg}}</div>
    {% endif %}
    <div class="row justify-content-end mx-5">
        <div class="col-6">
            <form action="{% url 'Renters:update_profile' user_info.id %}" method="post" class="d-flex flex-column gap-2" enctype="multipart/form-data">
                 {% csrf_token %}
                <div class="row"></div>
                <input name="first_name" class="form-control" type="text" minlength="3" required placeholder="First Name" value="{{user.first_name}}"/>
                <input name="last_name" class="form-control" type="text" minlength="3" required placeholder="Last Name" value="{{user.last_name}}"/>
                <input name="email" class="form-control" type="email" minlength="3" required placeholder="Email" value="{{user.email}}"/>
                <input name="phone" class="form-control mb-3" type="number" maxlength="10" required placeholder="phone" value="{{user.renter.phone}}"/>
                <textarea name="about" class="form-control" placeholder="about yourself">{{user.renter.about}}</textarea>
                <h4>Choose Avatar:</h4>
                <img src="{{user.renter.avatar.url}}" class="avatar" style="width: 100px;" />
                <input type="file" class="form-control" name="avatar" />
                <input type="submit" class="btn btn-warning" value="Update Profile" />
            </form>
        </div>
    </div>

</section>

{% endblock %}

CookSpaces/Renters/templates/renters/register_renter.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} Create Renter Account {% endblock %}

{% block style%}

{% endblock %}

{% block content %}


<section class="pb-lg-14 pb-6 px-5 mt-5 " style="background-color: #fff; direction: rtl; ">
    <div class="container">
      <div class=" row align-items-center ">
            <div class="col">
              <div >
                <form action="{% url 'Renters:register_renter' %}" method="post" class="d-flex flex-column gap-2" enctype="multipart/form-data" style=" padding: 30px; border-radius: 20px; border: 20px; ">
                    {% csrf_token %}
                    <h2 class="h1 fw-bold text-center"> <u class="text-warning "><span style="color: #232524;"> إنشاء حساب</span></u></h2>

                    <input name="username" class="form-control mb-3" type="text" minlength="3" required placeholder="اسم المستخدم" />
                    <div class="row mb-3">
                        <div class="col">
                            <input name="first_name" type="text" class="form-control" id="first_name" placeholder="الاسم الاول ..." required>
                        </div>

                        <div class="col">
                            <input name="last_name" type="text" class="form-control" id="last_name" placeholder=" الاسم الأخير ..." required>
                        </div>
                    </div>
                        <input name="email" class="form-control mb-3" type="email" required placeholder="ايميل" />
                        <input name="phone" class="form-control mb-3" type="number" maxlength="10" required placeholder="رقم الجوال" />
                        <textarea name="about" class="form-control mb-3" placeholder="أخبرنا عن نفسك"></textarea>
                        <label for="first_name" class="form-label" > صورة العرض:  </label>
                        <input type="file" class="form-control mb-3" name="avatar" />
                        <input name="password" class="form-control mb-3" type="password" minlength="6" required placeholder="الرقم السري" />
                        <input type="submit" class="btn btn mt-3" style="background-color: #00815b; color: #fff;" value="سجل الان" />
                    </form>

          </div>
        </div>
        <div class="col col-md-5 order-2 order-md-2 d-flex flex-column justify-content-center align-items-center">
          <div class="mb-6 mb-lg-0" style="background-color: #FFD4DD; border-radius: 60px;">
              <div class="mb-2" style="margin-right: 50px; "  >
                <img src="/static/images/signup_renter.jpeg" alt="certificate" class="img-fluid w-100" style="border-radius: 30px;">
              </div>

            </div>
          </div>
      </div>
    </div>

    </div>
 


</section>
{% endblock %}

CookSpaces/Renters/templates/renters/saved_kitchens.html
{% extends 'main/base.html' %}
{% block title %}CookSpaces | saved_kitchens{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
<section>
    <h1>{{user.username }}'s Favorites</h1>

    <div class="row">

        {% for favorite in user.bookmark_set.all %}
        <div class="col-4">
            <div class="d-flex flex-column gap-2 border border-1 shadow p-3 rounded-4 h-100">
                <img src="{{ favorite.kitchen.image.url }}"  class="w-100 rounded-4 card-poster "/>
                <h2><a href="{% url 'KitchenOwner:kitchen_details' favorite.kitchen.id  %}" class="text-decoration-none">{{favorite.kitchen.title}}</a></h2>   
            </div>
        </div>
        
    {% endfor %}

    </div>
</section>

{% endblock %}