CookSpaces/Chief/urls.py
from django.urls import path
from . import views

app_name = "Chief"

urlpatterns  = [
    path('Chief/register/', views.register_chife, name='register_chife'),
    path('Chief/profile/<user_name>', views.profile_view, name='profile'),
    path('Chief/all/', views.all_chief_view, name='all_chief_view'),
    path("Chief/update/", views.update_user_view, name="update_user_view"),


    


]

CookSpaces/CookSpaces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("", include("accounts.urls")),
    path("", include("KitchenOwner.urls")),
    path("", include("Renters.urls")),
    path("", include("Chief.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CookSpaces/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns  = [
    path("", views.home, name="home"),
    path("delete/<kitchen_id>", views.delete_kitchen, name="delete_kitchen"),
    path("articles/", views.all_article, name="articles"),
    path("articles/detail/<kitchen_id>", views.article_detail, name="article_detail"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path('contact/messages', views.messages, name='message'),
    path("reviews/add/<kitchen_id>", views.add_review, name="add_review"),
]

CookSpaces/Chief/models.py
from django.db import models

# Create your models here.

CookSpaces/Chief/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.models import User,Group
from django.contrib.auth import authenticate
from django.db import IntegrityError,transaction
from accounts.models import KitchenOwner,Renter,Chife

# Create your views here.
def register_chife(request:HttpRequest):
    msg = ""

    if request.method == "POST":
        try:

        
         with transaction.atomic():
                
                new_user = User.objects.create_user(username=request.POST["username"], email=request.POST["email"], first_name=request.POST["first_name"], last_name=request.POST["last_name"], password=request.POST["password"])
                new_user.save()

                if not new_user.groups.filter(name='Chef').exists():
                    group = Group.objects.get(name="Chef")
                    new_user.groups.add(group)
                
                profile= Chife(user=new_user,about=request.POST["about"] ,avatar=request.FILES.get("avatar", KitchenOwner.avatar.field.get_default()),phone=request.POST["phone"], cv=request.FILES.get("cv"))
                profile.save()

                
         return redirect("accounts:login")
        
        except IntegrityError as e:
            msg = "This username is already taken. Please choose a different username."
            print(e)

        except Exception as e:
            msg = f"Something went wrong {e}. Please try again."
            print(e)
    

    return render(request, "chief/register_chife.html", {"msg" : msg})


def  profile_view(request:HttpRequest, user_name):
    try:
        user_object = User.objects.get(username = user_name)
        
    except:
        return render(request, "404.html")


    return render(request, "chief/chief_profile.html", {"user_object":user_object})


def all_chief_view(request: HttpRequest):

    chife = Chife.objects.all()

    return render(request,"chief/all_chief.html", {'chife': chife})



def update_user_view(request: HttpRequest):
    msg = None

    if not request.user.is_authenticated:
        return redirect("accounts:login")
    
    try: 
        user_info = User.objects.get(pk=user_id)
    except:
        return render(request, "404.html")
    
    if request.method == "POST":
        
        try:

            with transaction.atomic():
                user:User = request.user

                user.first_name = request.POST["first_name"]
                user.last_name = request.POST["last_name"]
                user.email = request.POST["email"]

                user.save()
                
                try:
                    profile:Renter= user.renter
                except Exception as e:
                    profile =Renter(user=user)

                profile.about = request.POST["about"]
                profile.avatar = request.FILES.get("avatar", profile.avatar)

                profile.save()

                return redirect("Chief:profile", user_id=user.id)

        except Exception as e:
            msg = f"Something went wrong {e}"
            print(e)

    return render(request, "chief/update.html", {"user_info":user_info, "msg" : msg})

CookSpaces/Chief/templates/chief/all_chief.html
{% extends 'main/base.html' %}
{% block title %}All Chife{% endblock %}

{% block style %}
<style>
    .card {
      width: 17em;
      height: 22.5em;
      background: #f9f7f7;
      transition: 1s ease-in-out;
      clip-path: polygon(30px 0%, 100% 0, 100% calc(100% - 30px), calc(100% - 30px) 100%, 0 100%, 0% 30px);
      border-top-right-radius: 20px;
      border-bottom-left-radius: 20px;
      display: flex;
      flex-direction: column;
    }
    
    .card span {
      font-weight: bold;
      color: white;
      text-align: center;
      display: block;
      font-size: 1em;
    }
    
    .card .info {
      font-weight: 400;
      color: white;
      display: block;
      text-align: center;
      font-size: 0.72em;
      margin: 1em;
    }
    
    .card .img {
      width: 4.8em;
      height: 4.8em;
      background: white;
      border-radius: 15px;
      margin: auto;
    }
    
    .card .share {
      margin-top: 1em;
      display: flex;
      justify-content: center;
      gap: 1em;
    }
    
    .card a {
      color: white;
      transition: .4s ease-in-out;
    }
    
    .card a:hover {
      color: red;
    }
    
    .card button {
      padding: 0.8em 1.7em;
      display: block;
      margin: auto;
      border-radius: 25px;
      border: none;
      font-weight: bold;
      background: #ffffff;
      color: rgb(0, 0, 0);
      transition: .4s ease-in-out;
    }
    
    .card button:hover {
      background: red;
      color: white;
      cursor: pointer;
    }
    </style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 100px;">
        <div class="col-md-8">
            <h1>All Chife</h1>
            <div class="row">
                {% for Chife in chife %}
                  <div class="col d-flex justify-content-center" style="justify-items: center;">
                      <div class="card" style="width: 20rem;">
                          <img src="{{Chife.avatar.url}}" class="card-img-top" alt="">
                          <div class="card-body">
                             <h5 class="card-title">{{Chife.user.first_name}} {{Chife.user.last_name}}</h5>
                             <div class="d-flex justify-content-end">
                                  <a href="{% url 'Chief:profile' Chife.user.username %}" class="btn btn-outline-warning" style="color: #6E6A6A;">View Profile</a>
                             </div>
                          </div>
                       </div>
                  </div>
                 {% endfor %}
               </div>
             </div>
          </div>
</div>

{% endblock %}

CookSpaces/Chief/templates/chief/chief_profile.html
{% extends 'main/base.html' %}

{% block title %}Profile{% endblock %}

{% block styles %}
<style>
    .card{
    border:none;
    width: 735px;
    position:relative;
    border-radius:8px;
    cursor:pointer;
    margin-left: 200px;
}

.card:before{
    
    content:"";
    position:absolute;
    left:0;
    top:0;
    width:4px;
    height:100%;
    background-color:#E1BEE7;
    transform:scaleY(1);
    transition:all 0.5s;
    transform-origin: bottom
}

.card:after{
    
    content:"";
    position:absolute;
    left:0;
    top:0;
    width:4px;
    height:100%;
    background-color:#8E24AA;
    transform:scaleY(0);
    transition:all 0.5s;
    transform-origin: bottom
}

.card:hover::after{
    transform:scaleY(1);
}


.fonts{
    font-size:11px;
}

.social-list{
    display:flex;
    list-style:none;
    justify-content:center;
    padding:0;
}

.social-list li{
    padding:10px;
    color:#8E24AA;
    font-size:19px;
}


.buttons button:nth-child(1){
       border:1px solid #8E24AA !important;
       color:#8E24AA;
       height:40px;
}

.buttons button:nth-child(1):hover{
       border:1px solid #8E24AA !important;
       color:#fff;
       height:40px;
       background-color:#8E24AA;
}

.buttons button:nth-child(2){
       border:1px solid #8E24AA !important;
       background-color:#8E24AA;
       color:#fff;
        height:40px;
}
</style>
{% endblock %}

{% block content %}

<section>    
    <div class="row">
        
        <div class="col-md-7">
            
            <div class="card">
                
                <div class="text-center">
                  <img src="{{ user_object.chife.avatar.url }}" alt="Profile Image" class="img-fluid rounded-circle" style="width: 200px;">
                  <h5>@{{user_object.username}}</h5>

                </div>
                
                <div class="text-center mt-3">
                    <span class="bg-secondary px-3 rounded text-white">Pro</span>
                    <h3 style="text-transform: capitalize;">{{user_object.first_name}} {{ user_object.last_name}}</h3>
                    <a href="mailto:{{user_object.email}}">{{ user_object.email }}</a>
                    
                    
                    <div class="px-4 mt-1">
                      <p class="mt-2">{{ user_object.chife.about }}</p>
                      <a href="{{user_object.chife.cv}}" download><p>CV<i class="bi bi-download"></i></p></a>
                    </div>
                    
                     <ul class="social-list">
                        <li><i class="fa fa-facebook"></i></li>
                        <li><i class="fa fa-dribbble"></i></li>
                        <li><i class="fa fa-instagram"></i></li>
                        <li><i class="fa fa-linkedin"></i></li>
                        <li><i class="fa fa-google"></i></li>
                    </ul>
                    
                    <div class="buttons">
                        
                        <button class="btn btn-outline-primary px-4">Message</button>
                        <button class="btn btn-primary px-4 ms-3">Contact</button>
                    </div>
                </div>
                
               
                
                <div class=" d-flex justify-content-center align-items-center" >
                    {% if request.user == user_object %}
                        <a href="{% url 'Chief:update_user_view' user_object.id %}" class="btn btn-warning">Update</a>
                    {% endif %}
                </div>
            </div>
            
        </div>
        
    </div>
    
</section>
{% endblock %}

CookSpaces/Chief/templates/chief/register_chife.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} create Account {% endblock %}

{% block content %}


<section>
    {% if msg %}
    <div class="alert alert-danger">{{msg}}</div>
{% endif %}
<div class="row" >
    <h1 class="title" style="text-align: right; padding-top: 30px;"> <u class="text-warning"><span style="color: #283F31;">تسجيل جديد </span></u></h1>
    <div class="col-xl-5 col-lg-6 col-md-12 col-12">
        <div class="mb-6 " style="background-color: #FFD4DD; border-radius: 60px;">
          <div  style="margin-right: 50px; "  >
            <img src="/static/images/signup.jpeg" alt="certificate" class="img-fluid " style="border-radius: 30px; width: 550px; height: 650px;">
          </div>

        </div>
      </div>

    <div class="col-6" >
        <form action="{% url 'Chief:register_chife' %}" method="post" class="d-flex flex-column gap-2" enctype="multipart/form-data" style="direction: ltr; padding-top: 20px;">
            {% csrf_token %}

            <input name="username" class="form-control" type="text" minlength="3" required placeholder="اسم المستخدم" style="direction: rtl;"/>
            <input name="first_name" class="form-control" type="text" minlength="3" required placeholder="الاسم الاول" style="direction: rtl;"/>
            <input name="last_name" class="form-control" type="text" minlength="3" required placeholder="الاسم الاخير" style="direction: rtl;"/>
            <input name="email" class="form-control" type="email" minlength="3" required placeholder="الايميل" style="direction: rtl;"/>
            <input name="phone" class="form-control mb-3" type="number" maxlength="10" required placeholder="رقم الجوال" />
            <textarea name="about" class="form-control" placeholder=" تحدث عن نفسك" style="direction: rtl;"></textarea>
            <h6 style="direction: rtl;">السيرة الذاتية</h6>
            <input type="file" class="form-control" name="cv" style="direction: rtl;"/>


            <h6 style="direction: rtl;">اختر صورة</h6>
            <input type="file" class="form-control" name="avatar" style="direction: rtl;"/>

            <input name="password" class="form-control" type="password" minlength="6" required placeholder="الرقم السري" style="direction: rtl;"/>

            <input type="submit" class="btn btn mt-5" style="background-color: #283F31; color: antiquewhite;" value="Sign Up" />

        </form>
    </div>

</div>
</section>
   
{% endblock %}

CookSpaces/Chief/templates/chief/update.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} update {% endblock %}

{% block content %}



<section class="container mt-5">
    <h1>Update your profile</h1>

    {% if msg %}
        <div class="alert alert-danger" role="alert">
        {{ msg }}
        </div>
    {% endif %}
    <div class="row">
    
        <div class="col-6">

            <form class="d-flex flex-column gap-1" action="{% url 'Chief:update_user_view' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                
            <input name="username" class="form-control" type="text" minlength="3" required placeholder="اسم المستخدم" style="direction: rtl;"/>
            <input name="first_name" class="form-control" type="text" minlength="3" required placeholder="الاسم الاول" style="direction: rtl;"/>
            <input name="last_name" class="form-control" type="text" minlength="3" required placeholder="الاسم الاخير" style="direction: rtl;"/>
            <input name="email" class="form-control" type="email" minlength="3" required placeholder="الايميل" style="direction: rtl;"/>
            <input name="phone" class="form-control" type="number" minlength="3" required placeholder="رقم الجوال" style="direction: rtl;"/>

            <textarea name="about" class="form-control" placeholder=" تحدث عن نفسك" style="direction: rtl;"></textarea>
            <h6 style="direction: rtl;">السيرة الذاتية</h6>
            <input type="file" class="form-control" name="cv" style="direction: rtl;"/>


            <h6 style="direction: rtl;">اختر صورة</h6>
            <input type="file" class="form-control" name="avatar" style="direction: rtl;"/>


                <textarea class="form-control" name="about" placeholder="About you..">{{ request.user.profile.about }}</textarea>
                <div class="d-flex align-items-center gap-2 ">
                <img src="{{Chife.avatar.url }}" class="card-img-top" alt="Chife Image">

                <input class="form-control" type="file" name="avatar"  placeholder="choose avatar"/>
                </div>
                

                <input class="btn btn-primary" type="submit" value="Update profile" />
            </form>

        </div>

    </div>

</section>

{% endblock %}