CookSpaces/CookSpaces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("", include("accounts.urls")),
    path("", include("KitchenOwner.urls")),
    path("", include("Renters.urls")),
    path("", include("Chief.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CookSpaces/KitchenOwner/urls.py
from django.urls import path
from . import views

app_name = "KitchenOwner"

urlpatterns  = [
 path("kitchen/Owner/Register",views.register_owner,name="register_owner"),
 path("<owner_username>/profile",views.owner_profile,name="owner_profile"),
 path("add/kitchen",views.add_kitchen,name="add_kitchen"),
 path("<kitchen_id>/kitchen/details",views.kitchen_details,name="kitchen_details"),
 path("<owner_username>/update/profile",views.update_owner_profile,name="update_owner_profile"),
 path("All/kitchens/",views.all_kitchens,name="all_kitchens"),
 path("<kitchen_id>/rental/request/",views.rental_request,name="rental_request"),
 path("<owner_id>/orders/",views.owner_orders,name="owner_orders"),
 path("<order_id>/reject/order/",views.reject_order,name="reject_order"),
 path("<order_id>/accept/order/",views.accept_order,name="accept_order"),
 path("<order_id>/order/details/",views.order_details,name="order_details"),
 path("<order_id>/final/offer/",views.final_offer,name="final_offer"),
 path("All/kitchens/search/",views.search_cities,name="search_cities"),

]   

CookSpaces/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns  = [
    path("", views.home, name="home"),
    path("delete/<kitchen_id>", views.delete_kitchen, name="delete_kitchen"),
    path("articles/", views.all_article, name="articles"),
    path("articles/detail/<kitchen_id>", views.article_detail, name="article_detail"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path('contact/messages', views.messages, name='message'),
    path("reviews/add/<kitchen_id>", views.add_review, name="add_review"),
]

CookSpaces/KitchenOwner/models.py
from django.db import models
from accounts.models import KitchenOwner
# Create your models here.

class Equipment(models.Model):
   name = models.CharField(max_length=64, unique=True)
   # add icon field and delete quantity
   icon = models.CharField(max_length=64, default="")
   
   def __str__(self):
        return self.name
    
    
class Kitchen (models.Model):    
    #choices 
    periods = models.TextChoices("period",["شهري","سنوي"])
    status_choices = models.TextChoices("status",["accepted","rejected", "pending"])
    cities = models.TextChoices("city",['الرياض','جدة','الدمام'])
    
    kitchen_owner = models.ForeignKey(KitchenOwner,on_delete=models.CASCADE)
    title = models.CharField(max_length=1000)
    desc = models.TextField()
    image = models.ImageField(upload_to="posters/" ,default='posters/no_image.jpg')
    space = models.FloatField()
    
    has_ventilation = models.BooleanField(default=False)
    has_toilet = models.BooleanField(default=False)
    has_storage = models.BooleanField(default=False)
    has_waitingarea = models.BooleanField(default=False) 
    equipment = models.ManyToManyField(Equipment)
    loc_latitude = models.FloatField()
    loc_longitude = models.FloatField()
    price = models.FloatField()
    is_negotiable = models.BooleanField(default=False)
    city = models.CharField(max_length=100,choices=cities.choices)
    period = models.CharField(max_length=100,choices=periods.choices)
    status = models.CharField(max_length=100,choices=status_choices.choices)

    def __str__(self) -> str:
        return self.title    
    
class KitchenImage(models.Model):
    kitchen = models.ForeignKey(Kitchen,on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/")

CookSpaces/KitchenOwner/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.models import User,Group
from django.contrib.auth import authenticate
from django.db import IntegrityError,transaction
from accounts.models import KitchenOwner,Renter
from main.models import Review
from Renters.models import BookMark
from .models import Kitchen,Equipment
from Renters.models import Order
from django.conf import settings
from django.core.mail import EmailMessage


#kitchen owner register:
def register_owner(request:HttpRequest):
    msg = None

    if request.method == "POST":
        try:

        
            with transaction.atomic():
                
                user = User.objects.create_user(
                    username=request.POST["username"],
                    email=request.POST["email"],
                    first_name=request.POST["first_name"],
                    last_name=request.POST["last_name"],
                    password=request.POST["password"]
                    )
                user.save()
                if not user.groups.filter(name='Kitchen_owner').exists():
                    group = Group.objects.get(name="Kitchen_owner")
                    user.groups.add(group)

                
                register_owner = KitchenOwner(
                    user=user,
                    commercial_register=request.FILES.get("commercial_register"),
                    avatar=request.FILES.get("avatar", KitchenOwner.avatar.field.get_default()),
                    phone=request.POST["phone"],
                    verified=request.POST.get("verified",False)
                    )
                register_owner.save()

                
            return redirect("accounts:login")
        
        except IntegrityError as e:
            msg = "This username is already taken. Please choose a different username."
            print(e)

        except Exception as e:
            msg = f"Something went wrong. Please try again. {e}"
            print(e)
    

    return render(request, "KitchenOwner/register_owner.html", {"msg" : msg})

#kitchen owner profile:
def owner_profile(request : HttpRequest,owner_username):
    owner = KitchenOwner.objects.get(user__username=owner_username) 
    
    return render(request,"KitchenOwner/owner_profile.html",{"owner":owner})
    
#kitchen owner update profile:
def update_owner_profile(request :HttpRequest,owner_username):
    owner = KitchenOwner.objects.get(user__username=owner_username) 
    msg=""
    if request.method == "POST":
        try:
            with transaction.atomic():
                user = owner.user
                user.email = request.POST["email"]
                user.save()
                
                owner.commercial_register = request.FILES.get("commercial_register")
                owner.avatar = request.FILES.get("avatar",owner.avatar)
                owner.phone = request.POST["phone"]
                owner.save()
                return redirect("KitchenOwner:owner_profile",owner_username)
            
        except Exception as e :
            msg = f"something went wrong !{e.__class__} "
    
    return render(request,"KitchenOwner/update_owner_profile.html",{"owner":owner,"msg":msg})

def add_kitchen(request :HttpRequest):
    
    equipments = Equipment.objects.all()
    
    if request.method == "POST":
        
        lat =  float(request.POST.get("loc_latitude",False))
        lng = float(request.POST.get("loc_longitude",False))
        kitchen = Kitchen(
            kitchen_owner = request.user.kitchenowner,
            title = request.POST["title"],
            desc = request.POST["desc"],
            image = request.FILES.get("poster", Kitchen.image.field.default),
            space = request.POST["space"],
            
            #py default False 
            has_ventilation = request.POST.get("has_ventilation", False),
            has_toilet = request.POST.get("has_toilet", False),
            has_storage = request.POST.get("has_storage", False),
            has_waitingarea = request.POST.get("has_waitingarea", False),
            price = request.POST["price"],
            is_negotiable =request.POST.get("is_negotiable"),
            loc_latitude = lat,
            loc_longitude = lng,
            city = request.POST.get("city"),
            period = request.POST.get("period"),
            status = "pending"
        )
        kitchen.save()
        kitchen.equipment.set(request.POST.getlist("equipments",[]))
        
        return redirect("KitchenOwner:all_kitchens")
    return render(request,"KitchenOwner/add_kitchen.html",{"period":Kitchen.periods.choices,"equipments":equipments,"cities":Kitchen.cities.choices})

def kitchen_details(request :HttpRequest,kitchen_id):
    try:
        #getting a kitchen detail
        kitchen = Kitchen.objects.get(pk=kitchen_id)
        reviews = Review.objects.filter(kitchen=kitchen)
        is_saved = request.user.is_authenticated and  BookMark.objects.filter(user=request.user, kitchen=kitchen).exists()
        is_order=Order.objects.filter(renter__user__id=request.user.id,kitchen=kitchen,status="مقبولة").exists()
    except Kitchen.DoesNotExist:
        return render(request, "404.html")
    except Exception as e:
        print(e)
        
    return render(request, "kitchenowner/kitchen_details.html", {"kitchen" : kitchen, "reviews" : reviews, "is_saved" : is_saved,"is_order":is_order})
        
def all_kitchens(request :HttpRequest):
    kitchens = Kitchen.objects.all()
    
    return render(request,"KitchenOwner/all_kitchens.html",{"kitchens":kitchens})

def rental_request(request : HttpRequest,kitchen_id):
    kitchen=Kitchen.objects.get(id=kitchen_id)
    renter =Renter.objects.get(user=request.user)
    if request.method =="POST":
        order = Order(
            renter = renter,
            kitchen=kitchen,
            start_date = request.POST["start_date"],
            end_date=request.POST["end_date"],
            note = request.POST["note"],
            price=request.POST["price"],
            status="تحت المراجعة"
        )
        order.save()
        msg="Your request was successfully sent!"
        
    return render(request,"kitchenowner/kitchen_details.html",{"kitchen":kitchen,"msg":msg})

def owner_orders(request :HttpRequest,owner_id):
    orders = Order.objects.filter(kitchen__kitchen_owner__user__id=owner_id)
    
    return render (request,"KitchenOwner/owner_orders.html",{"orders":orders})

def reject_order(request:HttpRequest,order_id):
    order = Order.objects.get(id=order_id)
    owner_id = order.kitchen.kitchen_owner.user.id
    order.status = "مرفوضة"
    order.save()
    return redirect("KitchenOwner:owner_orders",owner_id)

def accept_order(request : HttpRequest, order_id):
    order = Order.objects.get(id=order_id)
    owner_id = order.kitchen.kitchen_owner.user.id
    order.status = "مقبولة"
    order.save()
    
    subject = 'حالة الطلب'
    message = f'السلام عليكم {order.renter.user.username},شكرا لاختيارك خدماتنا! نحن نقدر تفضيلك وثقتك بنا ونتطلع إلى خدمتك مرة أخرى قريبًا,تم قبول طلبك في منصة CookSpaces الرجاء التوجع الى صفحة طلباتك للدفع.'
    recipient_list = {order.renter.user.email}

    email = EmailMessage(subject, message, settings.EMAIL_HOST_USER, recipient_list)
    email.content_subtype = 'html'  # Enable HTML content
    try:
        email.send()
    except Exception as e:
        print(e)
    
    
    return redirect("KitchenOwner:owner_orders",owner_id)

def order_details(request : HttpRequest,order_id):
    order = Order.objects.get(id=order_id)

    return render(request,"KitchenOwner/order_details.html",{"order":order})

def final_offer(request :HttpRequest ,order_id):
    order = order = Order.objects.get(id=order_id)
    
    return render(request,"KitchenOwner/final_offer.html",{"order":order})

def search_cities(request):
    query = request.GET.get('city_search')
    if query:
        kitchens = Kitchen.objects.filter(city__icontains=query)
    else:
        kitchens = Kitchen.objects.all()
    return render(request, 'kitchenowner/all_kitchens.html', {'kitchens': kitchens})

CookSpaces/KitchenOwner/templates/kitchenowner/add_kitchen.html
{% extends "main/base.html" %}

{% block title %}Add Kitchen{% endblock %}

{% block content %}
<style>
#map {
    width:100%;
    height: 300px;
    background-color:cyan;
}
</style>



<section style="padding-top:150px;">
    <h2 class=" title h1 fw-bold"> <u class="text-warning"><span style="color: #00815b; margin-top: 500px; ">   إضافة مطبخ </span></u></h2>
    <form action="{% url 'KitchenOwner:add_kitchen'  %}" method="post" enctype="multipart/form-data" style="direction: rtl;">
        {% csrf_token %}
        
    <div class="row" >
        <div class="col-6" style="background-color: #F4F2EE; padding: 50px; ">
                <div class="d-flex flex-column gap-1 "> 
                <!--title-->
                 <h5>  <label for="title">تصنيف المطبخ</label> </h5>  
                <input type="text" name="title" placeholder="العنوان" style="border-radius: 10px;">
                <!--Description-->
                <textarea name="desc" cols="30" rows="5" placeholder="     وصف     " style="direction: rtl; border-radius: 10px;"></textarea>
                <br>
                <h5>  <label for="poster">صورة المطبخ</label> </h5> 
                <input type="file" accept="image/*" name="poster" aria-label="اختر صورة">
                <br>
                <!--space-->
                <h5><label for="space" >المساحة بالمتر<sup>2</label></h5> 
                <input type="text" name="space" style="border-radius: 10px;">
            </div>
            <div style="direction: rtl;">
                <br>
                <h5>مدة الاستئجار</h5>
                <select class="form-select" name="period" style=" border-radius: 10px; ">
                    <option value="Monthly" >شهري  </option>
                    <option value="Annually">سنوي  </option>
                </select>
            </div>
        
        </div>
        
        <div class="col-6" style="background-color: #F4F2EE; padding: 50px;">
            <div class="row">
                <div class="col">
                    <h5 style="direction: rtl;">الأجهزة</h5>
                    {% for e in equipments %}
                    <div class="d-flex gap-2" style="direction: rtl;">
                        <input type="checkbox" name="equipments" id="{{e.id}}" value="{{e.id}}" />
                        <label for="{{e.id}}" class="d-flex align-items-center gap-1">
                            <span class="material-symbols-outlined">{{e.icon}}</span>
                            <h6 class="m-0 p-0">{{e.name}}</h6>
                        </label>
                    </div>
                    {% endfor %}
                </div>
                <div class="col">

                    <h5 style="direction: rtl;">الخدمات</h5>
                    <!--has_ventilation-->
                    <div class="d-flex gap-2 " style="direction: rtl;">
                        <input type="checkbox" name="has_ventilation" value="True"> تهوية<br>
                    </div>
                    <!--has_toilet-->
                    <div class="d-flex gap-2 " style="direction: rtl;" >
                        <input type="checkbox" name="has_toilet" value="True">  دورة مياة<br>
                    </div>
                    
                    <!--has_storage-->
                    <div class="d-flex gap-2 " style="direction: rtl;">
                        <input type="checkbox" name="has_storage" value="True"> مخزن<br>
                    </div>
                    
                    <!--has_waitingarea-->
                    <div class="d-flex gap-2 " style="direction: rtl;">
                        <input type="checkbox" name="has_waitingarea" value="True"> استراحة<br>
                    </div>
                </div>
            </div>
            <br>
              <!--is_negotiable-->
            <div style="direction: rtl;">
                <h5>السعر قابل للتفاوض</h5>
                <input type="radio" name="is_negotiable" value="True">
                <label for="html">نعم</label><br>
                <input type="radio" name="is_negotiable" value="False">
                <label for="css">لا</label><br>
            </div>   

            <input type="text" hidden name="loc_latitude" id="lat" />
            <input type="text" hidden name="loc_longitude" id="lng" />
            <br>
                <!--price-->
                <h5 style="direction: rtl;">السعر</h5>
                <label for="price" ><input class="text-end" type="text" name="price" style="direction: rtl; border-radius: 10px; ">   ريال سعودي<br></label>
            <div style="direction: rtl; ">
                <br>
                <h5>المدينة</h5>
                <select name="city" class="form-select" required style="border-radius: 10px;">
                    {% for city,val in cities  %}
                        <option value="{{val}}">{{city}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>


        
    <div class="row">
        <div class="col text-center">
                <br>
                <br>
            <div id="map"></div>
            <input type="submit" class="btn btn-outline-warning" value="إضافة مطبخ" style="color: #00815b; margin-top: 30px;">
         </div>

        </div>
    </div>
    </form>
</section>










<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA1xTP268Ltwj4NX1Hku24XNFPJNZ-kTSQ&callback=initMap" async defer></script>
<script type="text/javascript">
        // JavaScript code goes here

let currentMarker = null; // Marker reference to keep track of the existing marker


function initMap() {
    var mapOptions = {
        center: {lat: 24.9764301, lng:46.6337875},  // Change this to your preferred initial center
        zoom: 8
    };

    // Create a map object and specify the DOM element for display.
    var map = new google.maps.Map(document.getElementById('map'), mapOptions);

    // This event listener will call addMarker() function when the map is clicked.
    map.addListener('click', function(event) {
        addMarker(event.latLng, map);

    // Extract latitude and longitude.
            var lat = event.latLng.lat();
            var lng = event.latLng.lng();

            //assign the value to the lat & long inputs
            document.getElementById("lat").value = lat;
            document.getElementById("lng").value = lng;
        });
}

// Adds a marker to the map.
function addMarker(location, map) {
    // Add the marker at the clicked location.
    // If there's an existing marker, remove it
    if (currentMarker) {
        currentMarker.setMap(null);
    }
    // Add a new marker at the clicked location
    currentMarker = new google.maps.Marker({
        position: location,
        map: map
    });

    // Optionally re-center the map on the new marker
    //map.setCenter(location);
}
</script>
{% endblock  %}

CookSpaces/KitchenOwner/templates/kitchenowner/all_kitchens.html
{% extends "main/base.html" %}

{% block title %} all kitchens {% endblock  %}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 100px;">
        <div style="display: flex; justify-content: space-between; margin-bottom: 10px;">
            <h1>كل المطابخ ({{kitchens.count}})</h1>
            <form action="{% url 'KitchenOwner:search_cities' %}" class="p-2 gap-2 d-flex" role="search" method="get">
                <input class="form-control me-2" type="search" placeholder="البحث بالمدينة..." aria-label="Search" name="city_search" >
                <button class="btn btn-outline-dark" type="submit">بحث</button>
              </form>
        </div>
                    <hr>
                    {% for kitchen in kitchens %}
                        <div class="col-4 d-flex mt-2">
                            <div class="card" style="width: 20rem;">
                                <img src="{{kitchen.image.url}}" alt="poster" style="background-size: cover; height: 200px;">
                                <div class="card-body">
                                   <h5 class="card-title">{{kitchen.title}}</h5>
                                   <h6>المساحة: {{kitchen.space}} م<sup>2</h6>
                                   <h6>السعر: {{kitchen.price}} ريال سعودي/{{kitchen.period}}</h6>
                                   <h6> المدينة: {{kitchen.city}}</h6>
                                   <div class="d-flex justify-content-end">
                                        <a href="{% url 'KitchenOwner:kitchen_details' kitchen.id %}" class="btn btn-outline-warning" style="color: #6E6A6A;">التفاصيل</a>
                                   </div>
                                </div>
                             </div>
                        </div>
                    {% endfor %}
    </div>
</div>
{% endblock %}

CookSpaces/KitchenOwner/templates/kitchenowner/order_details.html
{% extends "main/base.html" %}

{% block title %}order details{% endblock%}

{% block content %}

<!--kitchen details-->
<section>
    <div class="row">
        <div class="col">
           <h1>المطبخ</h1>
            <h1>{{order.kitchen.title}}</h1>
            {{order.kitchen.price}}
            {{order.kitchen.desc}}
           {% for e in order.kitchen.equipment_set.all %}
           {{e.name}}
           {{e.icon}}
           {% endfor %}
        </div>
    </div>
</section>

<!--order details-->
<hr>
<section>
    <div class="row">
        <div class="col">
           <h1>الطلب</h1>
            <h1>{{order.note}}</h1>
            {{order.start_date}}
            {{order.end_date}}
        
        {% if request.user %}
            <div>
                <a href="{% url "KitchenOwner:reject_order" order.id %}" class="btn btn-danger">رفض</a>
                <a href="{% url "KitchenOwner:accept_order" order.id %}" class="btn btn-success">قبول</a>
            </div>
        {% endif %}

            
        </div>
    </div>

</section>


<!-- accept order-->


{% endblock  %}

CookSpaces/KitchenOwner/templates/kitchenowner/owner_orders.html
{% extends "main/base.html" %}

{% block title %}my orders {% endblock  %}

{% block content %}
<section>
    <div class="row">
        <div class="col d-flex flex-column gap-3">
            
            <div class="bg bg-success">
                <h2>الطلبات المقبولة</h2>
            </div>
            {% for order in orders  %}
            {% if order.status == "مقبولة" %}
            <div class="border border-dark">
                {{order.start_date}}
                {{order.end_date}}
                {% if order.note %}
                {{order.note}}
                {{order.renter.user.username}}
                {{order.kitchen.kitchen_owner.user.username}}
                {% endif %}
                {% endif %}
                {% endfor %}
            <div class="bg bg-secondary">
                <h2>الطلبات المعلقة</h2>
            </div>
            {% for order in orders  %}
            {% if order.status == "تحت المراجعة" %} 
            <div class="border border-dark">
                {{order.start_date}}
                {{order.end_date}}
                {% if order.note %}
                {{order.note}}
                {{order.renter.user.username}}
                {{order.kitchen.kitchen_owner.user.username}}
                <div>
                    <a href="{% url "KitchenOwner:reject_order" order.id %}" class="btn btn-danger">رفض</a>
                    <a href="{% url "KitchenOwner:accept_order" order.id %}" class="btn btn-success">قبول</a>
                    <a href="{% url "KitchenOwner:order_details" order.id %}">تفاصيل الطلب</a>
                </div>
                {% endif %}
                {% endif %}
                {% endfor %}
            <div class="bg bg-danger">
                <h2>الطلبات المرفوضة</h2>
            </div>
            {% for order in orders  %}
            {% if order.status == "مرفوضة" %} 

            <div class="border border-dark">
                {{order.start_date}}
                {{order.end_date}}
                {% if order.note %}
                {{order.note}}
                {{order.renter.user.username}}
                {{order.kitchen.kitchen_owner.user.username}}
                
            {% endif %}
            {% endif %}
            {% endfor %}

        </div>
    </div>
</section>

{% endblock  %}

CookSpaces/KitchenOwner/templates/kitchenowner/owner_profile.html
{% extends "main/base.html" %}

{% block title %}{{owner.user.first_name}}{% endblock  %}

{% block content %}
<section>

    <div class="row justify-content-center">
        <div class="col-4 px-5">
            <img src="{{owner.avatar.url}}" class="avatar w-100 rounded-4" />
            <h5>{{owner.user.first_name}}</h5>
            {% if request.user.is_authenticated and request.user == owner.user %}
            <div class=" d-flex justify-content-end align-items-center" >
                <a href="{% url "KitchenOwner:update_owner_profile" owner.user.username %}" class="btn btn-warning">Update</a>
            </div>
            {% endif %}
        </div>

        <div class="col-4">

            <div class="d-flex flex-column">
                <h3 style="text-transform: capitalize;">{{owner.user.first_name}} {{ user_object.last_name}}</h3>
                <a href="mailto:{{owner.user.email}}">{{ owner.user.email }}</a>
                <a href="{{owner.commercial_register}}" download><p>commercial register  <i class="bi bi-download"></i></p></a>
                <p>Phone:{{owner.phone}}</p>
                <p class="mt-2"></p>
            </div>
            <hr/>
        </div>
    </div>
</section>

{% endblock  %}

CookSpaces/KitchenOwner/templates/kitchenowner/register_owner.html
{% extends 'main/base.html' %}

{% block title %} create Account {% endblock %}
{% block style%}
<!-- <style>
.register{
    background-color: #F4F2EE;
}

</style> -->
{% endblock %}


{% block content %}

<!-- <main >

    <div style="
    margin-top: 100px;
    background-image: url('/static/images/signup.jpeg');
    background-size: cover;
    background-repeat: no-repeat;
    position: relative;
    height: 1000px;
    direction: rtl;">

    
    <div class="container ">
        <div class="row " >
            {% if msg %}
            <div class="alert alert-danger">{{msg}}</div>
            {% endif %}
            
            <div class="row" style=" margin-top: 80px; direction: rtl;">
                <div class="col-6">
                    <form action="{% url 'KitchenOwner:register_owner' %}" method="post" class="d-flex flex-column gap-2" enctype="multipart/form-data" style="background-color: #F4F2EE; padding: 30px; border-radius: 20px; border: 20px; ">
                        {% csrf_token %}
                        <h1 class="fw-light text-black mb-4  text-center"> انشاء حساب</h1>
                        <input name="username" class="form-control mb-3" type="text" minlength="3" required placeholder="اسم المستخدم" />
                        <div class="row mb-3">
                            <div class="col">
                                <input name="first_name" type="text" class="form-control" id="first_name" placeholder="الاسم الاول ..." required>
                            </div>

                            <div class="col">
                                <input name="last_name" type="text" class="form-control" id="last_name" placeholder=" الاسم الأخير ..." required>
                            </div>
                        </div>
                            <input name="email" class="form-control mb-3" type="email" required placeholder="Email" />
                            <input name="phone" class="form-control mb-3" type="number" maxlength="10" required placeholder="رقم الجوال" />
                            <textarea name="about" class="form-control mb-3" placeholder="أخبرنا عن نفسك"></textarea>
                            <label for="first_name" class="form-label" > صورة العرض:  </label>
                            <input type="file" class="form-control mb-3" name="avatar" />
                            <input name="password" class="form-control mb-3" type="password" minlength="6" required placeholder="الرقم السري" />
                            <input type="submit" class="btn btn mt-3" style="background-color: #00815b; color: #fff;" value="سجل الان" />
                        </form>
                    </div>
                </div>
        </div>
    </div>
</div>
</main> -->

<section class="pb-lg-14 pb-6 px-5 mt-5 " style="background-color: #fff; direction: rtl; ">
    <div class="container">
      <div class=" row align-items-center ">
            <div class="col">
              <div >
                <form action="{% url 'KitchenOwner:register_owner' %}" method="post" class="d-flex flex-column gap-2" enctype="multipart/form-data" style=" padding: 30px; border-radius: 20px; border: 20px; ">
                    {% csrf_token %}
                    <h2 class="h1 fw-bold text-center"> <u class="text-warning "><span style="color: #232524;"> إنشاء حساب</span></u></h2>

                    <input name="username" class="form-control mb-3" type="text" minlength="3" required placeholder="اسم المستخدم" />
                    <div class="row mb-3">
                        <div class="col">
                            <input name="first_name" type="text" class="form-control" id="first_name" placeholder="الاسم الاول ..." required>
                        </div>

                        <div class="col">
                            <input name="last_name" type="text" class="form-control" id="last_name" placeholder=" الاسم الأخير ..." required>
                        </div>
                    </div>
                        <input name="email" class="form-control mb-3" type="email" required placeholder="Email" />
                        <input name="phone" class="form-control mb-3" type="number" maxlength="10" required placeholder="رقم الجوال" />
                        <textarea name="about" class="form-control mb-3" placeholder="أخبرنا عن نفسك"></textarea>

                        <label for="first_name" class="form-label" >ملف السجل التجاري </label>
                        <input type="file" class="form-control mb-3" name="avatar" />

                        <label for="first_name" class="form-label" > صورة العرض:  </label>
                        <input type="file" class="form-control mb-3" name="avatar" />
                        <input name="password" class="form-control mb-3" type="password" minlength="6" required placeholder="الرقم السري" />
                        <input type="submit" class="btn btn mt-3" style="background-color: #00815b; color: #fff;" value="سجل الان" />
                    </form>
          </div>
        </div>
        <div class="col col-md-5 order-2 order-md-2 d-flex flex-column justify-content-center align-items-center">
          <div class="mb-6 mb-lg-0" style="background-color: #FFD4DD; border-radius: 60px;">
              <div class="mb-2" style="margin-right: 50px; "  >
                <img src="/static/images/signup_owner.jpeg" alt="certificate" class="img-fluid w-100" style="border-radius: 30px;">
              </div>

            </div>
          </div>
      </div>
    </div>

    </div>
 


</section>
    
{% endblock %}